/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IConfidentialToken } from "./IConfidentialToken";
export type { WhisprPayroll } from "./WhisprPayroll";
