/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as whisprPayrollSol from "./WhisprPayroll.sol";
export type { whisprPayrollSol };
export type { ConfidentialUSDC } from "./ConfidentialUSDC";
export type { ConfidentialUSDT } from "./ConfidentialUSDT";
export type { WhisprPayrollFactory } from "./WhisprPayrollFactory";
