/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WhisprPayrollFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "createPayroll"
      | "getPayrollContractAt"
      | "getPayrollContractCount"
      | "getPayrollContracts"
      | "isWhisprPayroll"
      | "owner"
      | "renounceOwnership"
      | "setTokenAddress"
      | "tokenAddress"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PayrollCreated"
      | "TokenAddressUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPayroll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayrollContractAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayrollContractCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayrollContracts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhisprPayroll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayrollContractAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayrollContractCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayrollContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhisprPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollCreatedEvent {
  export type InputTuple = [
    payrollContract: AddressLike,
    employer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    payrollContract: string,
    employer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    payrollContract: string;
    employer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAddressUpdatedEvent {
  export type InputTuple = [newTokenAddress: AddressLike];
  export type OutputTuple = [newTokenAddress: string];
  export interface OutputObject {
    newTokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WhisprPayrollFactory extends BaseContract {
  connect(runner?: ContractRunner | null): WhisprPayrollFactory;
  waitForDeployment(): Promise<this>;

  interface: WhisprPayrollFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createPayroll: TypedContractMethod<
    [_employer: AddressLike],
    [string],
    "nonpayable"
  >;

  getPayrollContractAt: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getPayrollContractCount: TypedContractMethod<[], [bigint], "view">;

  getPayrollContracts: TypedContractMethod<
    [_employer: AddressLike],
    [string[]],
    "view"
  >;

  isWhisprPayroll: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTokenAddress: TypedContractMethod<
    [_tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  tokenAddress: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPayroll"
  ): TypedContractMethod<[_employer: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getPayrollContractAt"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPayrollContractCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayrollContracts"
  ): TypedContractMethod<[_employer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isWhisprPayroll"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenAddress"
  ): TypedContractMethod<[_tokenAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayrollCreated"
  ): TypedContractEvent<
    PayrollCreatedEvent.InputTuple,
    PayrollCreatedEvent.OutputTuple,
    PayrollCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAddressUpdated"
  ): TypedContractEvent<
    TokenAddressUpdatedEvent.InputTuple,
    TokenAddressUpdatedEvent.OutputTuple,
    TokenAddressUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayrollCreated(address,address,uint256)": TypedContractEvent<
      PayrollCreatedEvent.InputTuple,
      PayrollCreatedEvent.OutputTuple,
      PayrollCreatedEvent.OutputObject
    >;
    PayrollCreated: TypedContractEvent<
      PayrollCreatedEvent.InputTuple,
      PayrollCreatedEvent.OutputTuple,
      PayrollCreatedEvent.OutputObject
    >;

    "TokenAddressUpdated(address)": TypedContractEvent<
      TokenAddressUpdatedEvent.InputTuple,
      TokenAddressUpdatedEvent.OutputTuple,
      TokenAddressUpdatedEvent.OutputObject
    >;
    TokenAddressUpdated: TypedContractEvent<
      TokenAddressUpdatedEvent.InputTuple,
      TokenAddressUpdatedEvent.OutputTuple,
      TokenAddressUpdatedEvent.OutputObject
    >;
  };
}
