/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfidentialToken,
  IConfidentialTokenInterface,
} from "../../../src/WhisprPayroll.sol/IConfidentialToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "euint64",
        name: "amount",
        type: "bytes32",
      },
    ],
    name: "confidentialTransferFrom",
    outputs: [
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConfidentialToken__factory {
  static readonly abi = _abi;
  static createInterface(): IConfidentialTokenInterface {
    return new Interface(_abi) as IConfidentialTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfidentialToken {
    return new Contract(address, _abi, runner) as unknown as IConfidentialToken;
  }
}
