/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IConfidentialToken__factory } from "./IConfidentialToken__factory";
export { WhisprPayroll__factory } from "./WhisprPayroll__factory";
